$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: george-mlops-endpoint
model: azureml:stock-pred-lstm:2
code_configuration:
  code: ../
  scoring_script: score_azure.py
environment:
  conda_file: ../env_azure.yml
  image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04:latest
instance_type: Standard_D2as_v4
instance_count: 1
